"""Offline reference fixtures from pinned Doc2SoarGraph, empty-scale single spans.

Generated by calling the reviewed original TATEmAndF1 __call__ path; its only
substitution is an asserted 1x1 assignment (necessarily indices 0, 0). No local
metric helper generates expected scores. See docs/tatdqa_metric_provenance.md.
"""
import importlib.util
import inspect
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
SPEC = importlib.util.spec_from_file_location("tatdqa_metrics", ROOT / "experiments" / "tatdqa_metrics.py")
metrics = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(metrics)

# prediction, target, upstream exact match, upstream token-set F1
UPSTREAM_FIXTURES = [
    ('The Finance Group', 'finance group', 1.0, 1.0),
    ('cash flows', 'operating cash flows', 0.0, 0.8),
    ('a large red car', 'the large blue car', 0.0, 0.67),
    ('the', 'a', 1.0, 1.0),
    ('', '', 0.0, 0.0),
    ('', 'revenue', 0.0, 0.0),
    (' ', '', 1.0, 1.0),
    ('\t\n', '', 1.0, 1.0),
    ('', ' ', 0.0, 0.0),
    ('the', '', 1.0, 1.0),
    ('N/A', 'na', 1.0, 1.0),
    ('A&B Co.', 'ab co', 1.0, 1.0),
    ('revenue-cost', 'revenue cost', 0.0, 0.0),
    ('FOO\tBAR', 'foo bar', 1.0, 1.0),
    (' foo  bar\n', 'foo bar', 1.0, 1.0),
    ('2019', '2018', 0.0, 0.0),
    ('2019 revenue', '2018 revenue', 0.0, 0.5),
    ('2019  revenue', '2018 revenue', 0.0, 0.5),
    ('1,234', '1234', 1.0, 1.0),
    ('$1,234.00', '1234', 1.0, 1.0),
    ('12%', '0.12', 1.0, 1.0),
    ('12 percent', '0.12', 1.0, 1.0),
    ('12', '12%', 0.0, 0.0),
    ('0.12', '12%', 1.0, 1.0),
    ('12.345', '12.35', 1.0, 1.0),
    ('12.345%', '0.12345', 0.0, 0.0),
    ('(134)', '-134', 1.0, 1.0),
    ('(1,234)', '-1234', 0.0, 0.0),
    ('(12.5%)', '-0.125', 0.0, 0.0),
    ('(-12)', '12', 0.0, 0.0),
    ('12 million', '12000000', 1.0, 1.0),
    ('12', '12 million', 0.0, 0.0),
    ('2.5 billion', '2500000000', 1.0, 1.0),
    ('1e3', '1000', 0.0, 0.0),
    ('.5', '0.5', 0.0, 0.0),
    ('-.5', '-0.5', 0.0, 0.0),
    ('NaN', 'nan', 1.0, 1.0),
    ('inf', 'None', 0.0, 0.0),
    ('foo foo bar', 'foo bar', 0.0, 1.0),
    ('bar foo', 'foo bar', 0.0, 1.0),
    ('blue', 'red', 0.0, 0.0),
    ('word...', 'word', 1.0, 1.0),
    ('17/09/2026', '17/09/2026', 1.0, 1.0),
    ('2026-09-17', '2026 09 17', 0.0, 0.0),
    ('café', 'cafe', 0.0, 0.0),
    ('−12', '-12', 0.0, 0.0),
    ('“Alpha”', 'Alpha', 0.0, 0.0),
    ('one hundred', '100', 0.0, 0.0),
]


@pytest.mark.parametrize("prediction,target,em,f1", UPSTREAM_FIXTURES)
def test_matches_pinned_upstream_fixtures(prediction, target, em, f1):
    assert metrics.score_official(prediction, target) == {
        "official_em": em, "official_f1": f1,
    }


def test_numpy_half_rounding_matches_author_evaluator():
    predicted = "shared other"
    target = " ".join(["shared"] + [f"g{i}" for i in range(77)])
    # F1 is 2/(2+78) = .025. NumPy yields .02; Python round(float, 2) yields .03.
    assert metrics.score_official(predicted, target) == {"official_em": 0.0, "official_f1": 0.02}


def test_no_target_scale_is_supplied_to_prediction():
    assert list(inspect.signature(metrics.score_official).parameters) == ["prediction", "target"]
    assert metrics.score_official("12", "12 million") == {"official_em": 0.0, "official_f1": 0.0}
    assert metrics.score_official("12", "12%") == {"official_em": 0.0, "official_f1": 0.0}
    with pytest.raises(TypeError):
        metrics.score_official("12", "12", gold_scale="million")


@pytest.mark.parametrize("bad", [None, 12, 0.12, ["answer"], {"answer": "answer"}, True])
def test_rejects_non_string_or_multispan_inputs(bad):
    with pytest.raises(TypeError, match="single-span strings"):
        metrics.score_official(bad, "answer")
    with pytest.raises(TypeError, match="single-span strings"):
        metrics.score_official("answer", bad)


def test_provenance_and_float_outputs():
    assert metrics.UPSTREAM_COMMIT == "71a02715849942b79c1f74934a139e4b56fc6826"
    assert set(metrics.UPSTREAM_SHA256) == {"tatqa_metric.py", "tatqa_utils.py", "LICENSE"}
    assert all(len(value) == 64 for value in metrics.UPSTREAM_SHA256.values())
    assert all(type(value) is float for value in metrics.score_official("answer", "answer").values())
